
on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master

name: "Build and Deploy"
jobs: 
  build:
    name: "Build and Deploy"
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.0"
          channel: 'stable'
          cache: true
      - name: Run Pub Get
        run: flutter pub get
      - name: Generate model and cubit
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: Run Tests
        run: flutter test
      - name: Build APK
        run: flutter build apk
      - name: Push to Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/*"
          token: ${{ secrets.TOKEN }}
          tag: ${{ github.ref }} 
          
  
